# Generated by Django 4.2 on 2023-04-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("reference_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(max_length=128)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("duration", models.TimeField()),
                ("details", models.TextField(help_text="What is your event aboout?")),
            ],
        ),
        migrations.CreateModel(
            name="QR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_event_s", models.CharField(max_length=255)),
                ("id_ticket_s", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=128)),
                ("telephone", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id_moderator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ticket_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Planner",
            fields=[
                (
                    "id_planner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ticket_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_name", models.CharField(max_length=32)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("date_generated", models.DateTimeField(auto_now=True)),
                ("ticket_numer", models.IntegerField()),
                ("n_assistants", models.SmallIntegerField(default=1)),
                ("reusable", models.BooleanField(default=False)),
                (
                    "email_assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_app.assistant",
                    ),
                ),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_app.event",
                    ),
                ),
                (
                    "id_moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_app.moderator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moderator",
            name="id_planner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticket_app.planner"
            ),
        ),
        migrations.CreateModel(
            name="Event_Moderators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_app.event",
                    ),
                ),
                (
                    "id_moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket_app.moderator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assistant",
            name="id_mod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticket_app.moderator"
            ),
        ),
    ]
