# Generated by Django 4.2 on 2023-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
