# Generated by Django 4.2 on 2023-05-23 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket_app", "0002_alter_event_end_date_alter_event_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="id_planner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket_app.planner",
            ),
            preserve_default=False,
        ),
    ]
